name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build plaid-client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          platforms: linux/amd64
          push: true
          tags: melalj/plaid-client:latest,melalj/plaid-client:${{steps.vars.outputs.tag}}
      -
        name: Build plaid-server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: melalj/plaid-server:latest,melalj/plaid-server:${{steps.vars.outputs.tag}}
