name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          platforms: linux/amd64
          push: true
          tags: tonoid/plaid-client:latest,tonoid/plaid-client:${{steps.vars.outputs.tag}}
      -
        name: Build server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: tonoid/plaid-server:latest,tonoid/plaid-server:${{steps.vars.outputs.tag}}
